#!/bin/bash
mkdir /root/alx-system_engineering-devops/0x00-shell_basics/welcome/ /root/alx-system_engineering-devops/0x00-shell_basics/welcome/to/ /root/alx-system_engineering-devops/0x00-shell_basics/welcome/to/school
