#!/bin/bash 
-rwxr--r-- 1 root root 64 Mar  8 14:15 0-current_working_directory -rwxr--r-- 1 root root 62 Mar  8 14:22 1-listit -rwxr--r-- 1 root root 16 Mar  8 14:06 2-bring_me_home -rw-r--r-- 1 root root  0 Mar  8 14:24 3-listfiles -rw-r--r-- 1 root root 65 Mar  8 13:57 README.m
